import React from 'react'

import './globals.css'
import { Oxygen } from 'next/font/google'
import Navbar from '../app/common-components/navbar'
import Providers from './provider/provider'


const oxygen = Oxygen({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={oxygen.className}>
        <Providers>
          {children}
        </Providers>
        <Navbar />
      </body>
    </html>
  )
}
